// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Hybrid approach: grouped auto-generated sections with visual dividers
  tutorialSidebar: [
    'overview',  // Add explicit reference to overview.md at docs root
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    // Core Documentation Group
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Get started</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'overview',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Flamingock library configuration</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'flamingock-library-config',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Changes</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'changes',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Target Systems</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'target-systems',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Audit Stores</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'audit-stores',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Safety and Recovery</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'safety-and-recovery',
    },
    // {
    //   type: 'html',
    //   value: '<hr class="sidebar-divider" />',
    // },
    // {
    //   type: 'html',
    //   value: '<div class="sidebar-contents-header">Cloud Edition</div>',
    // },
    // {
    //   type: 'autogenerated',
    //   dirName: 'cloud-edition',
    // },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Templates</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'templates',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    // Framework Integration Group
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Supported frameworks</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'frameworks',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    // Advanced Topics Group
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Testing</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'testing',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Command Line Interface</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'cli',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Resources</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'resources',
    },
  ],
};

export default sidebars;
