// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Hybrid approach: grouped auto-generated sections with visual dividers
  tutorialSidebar: [

    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    // Core Documentation Group
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Overview</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'overview',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Flamingock library</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'flamingock-library-config',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Templates</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'templates',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    // Framework Integration Group
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Supported frameworks</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'frameworks',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    // Edition-Specific Group
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Community Edition</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'community-edition',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Cloud Edition</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'cloud-edition',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    // Advanced Topics Group
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Testing</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'testing',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Command Line Interface</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'cli',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Examples</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'examples',
    },
    {
      type: 'html',
      value: '<hr class="sidebar-divider" />',
    },
    {
      type: 'html',
      value: '<div class="sidebar-contents-header">Migration guide</div>',
    },
    {
      type: 'autogenerated',
      dirName: 'migration',
    },
  ],
};

export default sidebars;
